name: Build and Push Odoo Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: tefaalex
          password: ${{ DOCKER_HUB_TOK }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tefaalex/odoo-custom:latest
          file: ./Dockerfile

      # Verify the health check of the container
      - name: Run health check
        run: |
          docker run -d -p 8069:8069 --name odoo-container ${{ secrets.DOCKER_USERNAME }}/odoo-custom:latest
          sleep 10 # Wait for container to start
          docker exec odoo-container curl --fail http://localhost:8069/web/health || exit 1
