name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '16.0'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.CI_REGISTRY_USER }}
          DOCKER_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login "${{ secrets.CI_REGISTRY }}" --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker Image
        id: build_image
        run: |
          image_name="${{ secrets.CI_REGISTRY_IMAGE }}" # Set your image name here
          if [ "${{ github.ref }}" == "refs/heads/16.0" ]; then
            tag="" # No tag for the latest version
            echo "Running on branch '16.0': tag = 'latest'" 
          else
            tag=":latest" # Tag for other branches
            echo "Running on branch '${{ github.ref }}': tag = $tag"
          fi
          # Build the Docker image
          docker build --pull -t "${image_name}${tag}" -f build_tools/Dockerfile .

      - name: Push Docker Image
        run: |
          image_name="${{ secrets.CI_REGISTRY_IMAGE }}"
          docker push "${image_name}${{ github.ref == 'refs/heads/16.0' && echo '' || echo ':latest' }}"
